services:

  db_pg_py:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_pg-data:/var/lib/postgresql/data
    shm_size: 128mb
    container_name: db_pg_py
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend
    
  traefik:
    image: traefik:v2.9
    container_name: traefik
    ports:
      - "9999:9999"  # Porta de entrada única
      - "8080:8080"  # Dashboard do Traefik
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic
      - ./traefik.log:/var/log/traefik/traefik.log
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - payment-processor

 # Template do py_rinha
  go_rinha_template: &go_rinha_template
    build: ./
    networks:
      - backend
      - payment-processor
    depends_on:
      db_pg_py:
        condition: service_healthy
    expose:
      - "9999"
    environment:
      - PG_DSN=user=postgres password=password host=db_pg_py port=5432 dbname=postgres sslmode=disable
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis_py
      - REDIS_PORT=6379
      - REDIS_KEY=healthy

  go_rinha_1:
    <<: *go_rinha_template
    container_name: go_rinha_1

  go_rinha_2:
    <<: *go_rinha_template
    container_name: go_rinha_2



volumes:
  db_pg-data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true  