# Template do py_rinha
x-templates:
  go_rinha_template: &go_rinha_template
    build: api/
    networks:
      - backend
      - payment-processor
    depends_on:
      pgbouncer:
        condition: service_healthy
    restart: always
    expose:
      - "9999"
    environment:
      - PG_DSN=user=postgres password=password host=pgbouncer port=6432 dbname=postgres sslmode=disable
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=payments_topic
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: "80MB"

services:

  db_pg_py:
    image: postgres:14-alpine
    restart: always
    command: -c 'max_connections=200'
    volumes:
      - db_pg-data:/var/lib/postgresql/data
    shm_size: 128mb
    container_name: db_pg_py
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: "60MB"

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "6432"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - db_pg_py
    networks:
      - backend
      - payment-processor
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: "30MB"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: "30MB"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    networks:
      - backend
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    restart: always
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "40MB"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go_rinha_1
      - go_rinha_2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "30MB"

  worker_rinha:
    build: worker/
    container_name: worker_rinha
    networks:
      - backend
      - payment-processor
    depends_on:
      pgbouncer:
        condition: service_healthy
    restart: always
    expose:
      - "9999"
    environment:
      - PG_DSN=user=postgres password=password host=pgbouncer port=6432 dbname=postgres sslmode=disable
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=payments_topic
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: "80MB"

  go_rinha_1:
    <<: *go_rinha_template
    container_name: go_rinha_1

  go_rinha_2:
    <<: *go_rinha_template
    container_name: go_rinha_2

volumes:
  db_pg-data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
