services:

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "200MB"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go_rinha_1
      - go_rinha_2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: "50MB"

  go_rinha_1: &go_rinha_template
    build: ./
    container_name: go_rinha_1
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    expose:
      - "9999"
    environment:
      - REDIS_URL=redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: "50MB"

  go_rinha_2:
    <<: *go_rinha_template
    container_name: go_rinha_2

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
