# Template do py_rinha
x-templates:
  go_rinha_template: &go_rinha_template
    build: ./
    networks:
      - backend
      - payment-processor
    depends_on:
      db_pg_py:
        condition: service_healthy
    restart: always
    expose:
      - "9999"
    environment:
      - PG_DSN=user=postgres password=password host=db_pg_py port=5432 dbname=postgres sslmode=disable
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis_py
      - REDIS_PORT=6379
      - REDIS_KEY=healthy
    cpus: "0.3"
    mem_limit: "60m"

services:

  db_pg_py:
    image: postgres:14-alpine
    restart: always
    command: -c 'max_connections=200'
    volumes:
      - db_pg-data:/var/lib/postgresql/data
    shm_size: 128mb
    container_name: db_pg_py
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - backend
    # cpus: "0.50"
    # mem_limit: "1530m"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go_rinha_1
      - go_rinha_2
    networks:
      - backend
      - payment-processor
    cpus: "0.40"
    mem_limit: "80m"

  go_rinha_1:
    <<: *go_rinha_template
    container_name: go_rinha_1

  go_rinha_2:
    <<: *go_rinha_template
    container_name: go_rinha_2



volumes:
  db_pg-data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true  